stages:
  - deploy

deploy:
  stage: deploy
  image: cafanwii/ssh-sshpass:v1.0.0
  script:
    - echo "$SSH_AUTH" > id_rsa
    - chmod 600 id_rsa

    - scp -o "StrictHostKeyChecking=no" -i id_rsa Dockerfile ubuntu@ec2-18-234-144-31.compute-1.amazonaws.com:testssh/
    - ssh -o "StrictHostKeyChecking=no" -i id_rsa ubuntu@ec2-18-234-144-31.compute-1.amazonaws.com "touch testssh/myfile.txt"

  only:
    - main


# save the private key as a variable [SSH_AUTH]
