variables:
  DOCKER_IMAGE_NAME: networking

stages:
  - build

workflow:
  rules:
    - if: '$CI_COMMIT_REF_NAME == "main"'

docker-job:
  stage: build
  retry:
    max: 2
    when:
      - script_failure
      - stuck_or_timeout_failure

  script:
    - docker login -u $ARTIFACTORY_USER $ARTIFACTORY_URL -p $ARTIFACTORY_API_TOKEN
    - docker build -t $CI_REGISTRY_IMAGE/${DOCKER_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID} .
    - docker tag $CI_REGISTRY_IMAGE/${DOCKER_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID} $ARTIFACTORY_URL/docker-trial/${DOCKER_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
    - docker push $ARTIFACTORY_URL/docker-trial/${DOCKER_IMAGE_NAME}:${CI_COMMIT_REF_SLUG}-${CI_PIPELINE_ID}
  only:
    - main
  tags:
    - cafanwii-group-runner
